name: Run android tests in github runner

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
            npm install -g appium@v1.22
            appium -v
            appium &>/dev/null &
      
      - name: Run Android tests on BrowserStack
        run: |
          mvn clean test -Pandroid
